spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple&prepareThreshold=0
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.wcvyfovaiigrkmzsqrpq
spring.datasource.password=!@!L1e2e34!!!
spring.datasource.hikari.connection-init-sql=SET search_path TO memo_board, public
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.default_schema=memo_board
spring.h2.console.enabled=false
spring.session.jdbc.initialize-schema=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/postgres
spring.flyway.schemas=memo_board
spring.flyway.default-schema=memo_board
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
