spring.datasource.url=${POSTGRES_JDBC_URL:}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USERNAME:}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.hikari.connection-init-sql=SET search_path TO memo_board, public
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.default_schema=memo_board
spring.h2.console.enabled=false
spring.session.jdbc.initialize-schema=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/postgres
spring.flyway.schemas=memo_board
spring.flyway.default-schema=memo_board
