spring.datasource.url=${LOCAL_DB_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${LOCAL_DB_USERNAME:postgres.wcvyfovaiigrkmzsqrpq}
spring.datasource.password=!@!L1e2e34!!!
app.datasource.password-fallback=!@!L1e2e34!!!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
