spring.application.name=SFOOD-MB-APP-V1

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.servlet.session.timeout=24h

logging.level.com.sfood.mb.app.controller=INFO
logging.level.com.sfood.mb.app.config.AuthInterceptor=INFO
