spring.application.name=SFOOD-MB-APP-V1
server.servlet.session.timeout=24h
logging.level.com.sfood.mb.app=INFO
spring.datasource.url=jdbc:h2:mem:sfoodmb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
