spring.application.name=SFOOD-MB-APP-V1
spring.profiles.default=local
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.session.store-type=jdbc
spring.session.timeout=24h
spring.session.jdbc.table-name=memo_board.SPRING_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
app.auth.google-verifier-mode=local
app.auth.google-token-info-url=https://oauth2.googleapis.com/tokeninfo
logging.level.com.sfood.mb.app=INFO
