app.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&preferQueryMode=simple}
app.datasource.username=${DB_USERNAME:postgres.wcvyfovaiigrkmzsqrpq}
app.datasource.password=${DB_PASSWORD:}
app.datasource.driver-class-name=org.postgresql.Driver
app.datasource.schema=${DB_SCHEMA:memo_board_v4}

spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:memo_board_v4}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-init.sql

logging.level.root=INFO
logging.level.com.sfood.mb.app=INFO
