{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.5.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.12-SNAPSHOT.jar",
          "url": "spring-boot-starter-test-3.5.12-SNAPSHOT.jar",
          "size": 4810,
          "sha512": "afd1b0a792e823ec5cae3f68f16d8522b9d741423d3ed6c03c30aacbbfa474ee1b1f7478b43ef6c0430b51f2371e3c12328c66925062e73d6002c3da0557bb70",
          "sha256": "abe8950d2675e32e31b7b4316aaecb3a0692a158e15daaf07097677b052d801a",
          "sha1": "7c5d8c58040e180ef4f10d466b84586e62a17f71",
          "md5": "223acdd790f7fee42284b694c421182c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.12-SNAPSHOT"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.12-SNAPSHOT.jar",
          "url": "spring-boot-starter-test-3.5.12-SNAPSHOT.jar",
          "size": 4810,
          "sha512": "afd1b0a792e823ec5cae3f68f16d8522b9d741423d3ed6c03c30aacbbfa474ee1b1f7478b43ef6c0430b51f2371e3c12328c66925062e73d6002c3da0557bb70",
          "sha256": "abe8950d2675e32e31b7b4316aaecb3a0692a158e15daaf07097677b052d801a",
          "sha1": "7c5d8c58040e180ef4f10d466b84586e62a17f71",
          "md5": "223acdd790f7fee42284b694c421182c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.12-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-test-3.5.12-SNAPSHOT-javadoc.jar",
          "size": 4810,
          "sha512": "f7ae1294312800b68d9f81df44fd08bbb1315a62bdc38db8fe4f049af4ac59d15b2de9eed1af460b62922f91d905e2f8c1d2679e1d55eeb2c9e3464fcd8c083b",
          "sha256": "dc43d4783bcc07f74a5fff4d6bb6dd0d0c1f4b9a374dc73da8e5df725730bad8",
          "sha1": "e2a3c758fc18cebbe9f803cef5c91a526fa5137a",
          "md5": "cb22339a680dec577f60856fdbde1a8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.12-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-test-3.5.12-SNAPSHOT-sources.jar",
          "size": 4810,
          "sha512": "f7ae1294312800b68d9f81df44fd08bbb1315a62bdc38db8fe4f049af4ac59d15b2de9eed1af460b62922f91d905e2f8c1d2679e1d55eeb2c9e3464fcd8c083b",
          "sha256": "dc43d4783bcc07f74a5fff4d6bb6dd0d0c1f4b9a374dc73da8e5df725730bad8",
          "sha1": "e2a3c758fc18cebbe9f803cef5c91a526fa5137a",
          "md5": "cb22339a680dec577f60856fdbde1a8e"
        }
      ]
    }
  ]
}
